[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jaxscape"
version = "0.0.6"
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
  { name = "Victor Boussange", email = "vic.boussange@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "equinox>=0.13.2",
    "jax[cuda]",
    "tqdm",
    "numpy",
    "pyamg>=5.1.0",
    "lineax>=0.0.8",
    "cholespy>=2.1.0",
]

[project.urls]
Documentation = "https://github.com/vboussange/jaxscape#readme"
Issues = "https://github.com/vboussange/jaxscape/issues"
Source = "https://github.com/vboussange/jaxscape"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "networkx>=3.5",
    "pytest>=8.3.5",
]
